# Generated by Django 5.0.6 on 2026-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("team_invite", "Team Invite"),
                    ("team_invite_accepted", "Team Invite Accepted"),
                    ("team_invite_rejected", "Team Invite Rejected"),
                    ("order_placed", "Order Placed"),
                    ("general", "General"),
                ],
                default="general",
                max_length=40,
            ),
        ),
    ]
