# Generated by Django 6.0.4 on 2026-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_plan_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("team_invite", "Team Invite"),
                    ("team_invite_accepted", "Team Invite Accepted"),
                    ("team_invite_rejected", "Team Invite Rejected"),
                    ("order_placed", "Order Placed"),
                    ("plan_expiring", "Plan Expiring"),
                    ("plan_expired", "Plan Expired"),
                    ("store_created", "Store Created"),
                    ("general", "General"),
                ],
                default="general",
                max_length=40,
            ),
        ),
    ]
