# Generated by Django 5.0.6 on 2026-08-11 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_store_domain_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_color", models.CharField(default="#a855f7", max_length=20)),
                ("secondary_color", models.CharField(default="#ffffff", max_length=20)),
                ("accent_color", models.CharField(default="#7e22ce", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#ffffff", max_length=20),
                ),
                ("text_color", models.CharField(default="#0f1117", max_length=20)),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("Inter", "Inter"),
                            ("Outfit", "Outfit"),
                            ("Poppins", "Poppins"),
                            ("Lato", "Lato"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                        ],
                        default="Inter",
                        max_length=50,
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("rounded", "Rounded"),
                            ("square", "Square"),
                            ("pill", "Pill"),
                        ],
                        default="rounded",
                        max_length=20,
                    ),
                ),
                (
                    "product_card_style",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("standard", "Standard"),
                            ("large", "Large"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "navigation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"links": [{"label": "Shop", "url": "/shop"}]}',
                    ),
                ),
                (
                    "footer",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"tagline": "...", "links": [...]}',
                    ),
                ),
                (
                    "announcement_bar",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"text": "Free shipping!", "enabled": true}',
                    ),
                ),
                (
                    "published_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Snapshot of the config at last publish. Served to customers.",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_config",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "storefront config",
                "verbose_name_plural": "storefront configs",
            },
        ),
        migrations.CreateModel(
            name="StorefrontSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("announcement_bar", "Announcement Bar"),
                            ("navbar", "Navbar"),
                            ("hero", "Hero"),
                            ("categories", "Categories"),
                            ("featured_products", "Featured Products"),
                            ("product_grid", "Product Grid"),
                            ("promo_banner", "Promo Banner"),
                            ("about", "About"),
                            ("testimonials", "Testimonials"),
                            ("newsletter", "Newsletter"),
                            ("footer", "Footer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "published_settings",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_sections",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "storefront section",
                "verbose_name_plural": "storefront sections",
                "ordering": ["order"],
                "unique_together": {("store", "type")},
            },
        ),
    ]
