# Generated by Django 6.0.4 on 2026-08-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storefrontsection",
            name="type",
            field=models.CharField(
                choices=[
                    ("announcement_bar", "Announcement Bar"),
                    ("navbar", "Navbar"),
                    ("hero", "Hero"),
                    ("categories", "Categories"),
                    ("featured_products", "Featured Products"),
                    ("product_grid", "Product Grid"),
                    ("catalog", "Catalog"),
                    ("promo_banner", "Promo Banner"),
                    ("about", "About"),
                    ("testimonials", "Testimonials"),
                    ("newsletter", "Newsletter"),
                    ("footer", "Footer"),
                ],
                max_length=50,
            ),
        ),
    ]
