# Generated by Django 5.0.6 on 2026-08-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_storefrontconfig_heading_font"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontconfig",
            name="layout",
            field=models.CharField(
                choices=[
                    ("classic", "Classic — hero, grid, about"),
                    ("editorial", "Editorial — full-bleed lookbook"),
                    ("boutique", "Boutique — split hero, filtered catalogue"),
                    ("menu", "Menu — tabbed sections, price list"),
                    ("techgrid", "Technical — spec panels, sidebar filters"),
                    ("showcase", "Showcase — no-photography cards"),
                    ("service", "Service — centred hero, offering list"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
