# Generated by Django 5.0.6 on 2026-08-11 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fashion", "Fashion"),
                            ("food", "Food & Beverage"),
                            ("electronics", "Electronics"),
                            ("beauty", "Beauty"),
                            ("general", "General"),
                            ("minimal", "Minimal"),
                            ("bold", "Bold"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="category",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="themes/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "preview_url",
                    models.URLField(blank=True, verbose_name="live preview URL"),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Defines customizable fields (colors, fonts, sections)",
                        verbose_name="configuration schema",
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        default=dict,
                        help_text="Default values for theme configuration",
                        verbose_name="default configuration",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=True, verbose_name="free tier"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "theme",
                "verbose_name_plural": "themes",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
