#!/usr/bin/env bash
# Regenerates snippets/cloudflare-real-ip.conf from Cloudflare's published ranges.
#
# Why this exists: with Cloudflare proxying, every connection reaches nginx from
# a Cloudflare address. Left alone, $remote_addr is that address, and the
# limit_req zones key on $binary_remote_addr — so the whole world shares a
# handful of buckets and the auth limiter throttles everyone the moment one
# person retries a login. That is the breakage this fixes.
#
# Django's DRF throttles are not in the same position, though it looks like they
# should be: SimpleRateThrottle.get_ident prefers HTTP_X_FORWARDED_FOR and only
# falls back to REMOTE_ADDR, and proxy-params.conf always sends that header, so
# they key per visitor either way. What this does for them is tidy the value —
# without it $proxy_add_x_forwarded_for appends Cloudflare's address to the
# visitor's, and the throttle bucket is the pair rather than the client.
#
# set_real_ip_from + real_ip_header CF-Connecting-IP restores the true client
# address, but only for connections that genuinely came from Cloudflare — which
# is why the range list has to be exact and current rather than 0.0.0.0/0.
#
# Cloudflare changes these rarely. Re-run when they announce a change, then
# `docker compose ... exec nginx nginx -s reload`.
set -euo pipefail
out="$(dirname "$0")/snippets/cloudflare-real-ip.conf"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by update-cloudflare-ips.sh — do not edit by hand."
  echo "# Source: https://www.cloudflare.com/ips-v4 and ips-v6"
  echo "#"
  echo "# Trust the CF-Connecting-IP header, but only from Cloudflare's own"
  echo "# ranges. Any other source keeps its real \$remote_addr, so someone"
  echo "# hitting the origin directly cannot spoof a client address."
  echo
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # `|| true` on the read: these files have no trailing newline, so the last
    # range is lost without it.
    while read -r cidr || [ -n "$cidr" ]; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done < <(curl -fsS "$url")
  done
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "wrote $out ($(grep -c set_real_ip_from "$out") ranges)"
