# Generated by Django 6.0.4 on 2026-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_settlement_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Flat delivery charge added on top of the line-item total.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The amount subtracted from the subtotal before delivery fee.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Colour, size, custom instructions — anything the buyer typed.",
                verbose_name="buyer notes",
            ),
        ),
    ]
