#!/usr/bin/env python3
"""Emit a bash script that writes the two production env files on the instance.

Run as:  python3 gen-prod-env.py | ssh <host> 'bash -s'

Values are never printed to a terminal or a log: this script's stdout is the
ssh process's stdin, and only a list of key *names* goes to stderr. Third-party
credentials are copied from backend/.env; SECRET_KEY and the Postgres password
are generated fresh, because a development key should not become a production
one and production.py rejects anything short or prefixed "django-insecure-".
"""
from __future__ import annotations

import secrets
import sys
from pathlib import Path

ROOT_DOMAIN = "koraa.africa"
API_HOST = f"api.{ROOT_DOMAIN}"
BUCKET = "koraa-africa-media"
REGION = "us-east-1"

REPO = Path(__file__).resolve().parents[2]
LOCAL_ENV = REPO / "backend" / ".env"

# Copied verbatim from backend/.env — these name real third-party accounts, so a
# fresh value would simply be wrong.
COPY_KEYS = [
    "EMAIL_BACKEND", "EMAIL_HOST", "EMAIL_PORT", "EMAIL_USE_TLS",
    "EMAIL_HOST_USER", "EMAIL_HOST_PASSWORD", "DEFAULT_FROM_EMAIL",
    "FAPSHI_API_USER", "FAPSHI_API_KEY", "FAPSHI_BASE_URL",
    "DIDIT_API_KEY",
    "OPENROUTER_API_KEY", "OPENROUTER_MODEL",
    "DEEPSEEK_API_KEY", "DEEPSEEK_MODEL", "DEEPSEEK_API_BASE_URL",
]


def read_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # django-environ does not strip quotes for every type, and a stray pair
        # would end up inside the secret itself.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        out[key] = value
    return out


local = read_env(LOCAL_ENV)

missing = [k for k in COPY_KEYS if not local.get(k)]
if missing:
    print(f"WARNING: absent or empty in backend/.env: {', '.join(missing)}",
          file=sys.stderr)

secret_key = secrets.token_urlsafe(64)
pg_password = secrets.token_urlsafe(32)

compose_env = {
    "POSTGRES_USER": "koraa",
    "POSTGRES_PASSWORD": pg_password,
    "POSTGRES_DB": "koraa",
}

backend_env: dict[str, str] = {
    "SECRET_KEY": secret_key,
    "DEBUG": "False",
    # 127.0.0.1 is for the container healthcheck; `backend` for the compose
    # network. See backend/.env.prod.example.
    "ALLOWED_HOSTS": (
        f"{ROOT_DOMAIN},www.{ROOT_DOMAIN},{API_HOST},.{ROOT_DOMAIN},"
        "backend,127.0.0.1"
    ),
    "KORAA_ROOT_DOMAIN": ROOT_DOMAIN,
    "KORAA_STOREFRONT_DOMAIN": ROOT_DOMAIN,
    "KORAA_DASHBOARD_URL": f"https://{ROOT_DOMAIN}",
    "KORAA_API_URL": f"https://{API_HOST}",
    "FIREBASE_PROJECT_ID": "koraa-a3ecd",
    # nginx redirects HTTP and forwards X-Forwarded-Proto, so True is correct.
    "SECURE_SSL_REDIRECT": "True",
    "CONN_MAX_AGE": "60",
    # Media on S3. Credentials are deliberately absent: base.py turns empty into
    # None and boto3 then reads the instance role from IMDS, so nothing
    # long-lived is written to disk.
    "USE_S3": "True",
    "AWS_STORAGE_BUCKET_NAME": BUCKET,
    "AWS_S3_REGION_NAME": REGION,
    "DJANGO_LOG_LEVEL": "INFO",
    # 2 vCPU: 3 workers x 2 threads, the image's own default, stated explicitly.
    "GUNICORN_WORKERS": "3",
    "GUNICORN_THREADS": "2",
    # Must stay above the 15s Fapshi client timeout.
    "GUNICORN_TIMEOUT": "60",
    "GUNICORN_LOG_LEVEL": "info",
}
for key in COPY_KEYS:
    if local.get(key):
        backend_env[key] = local[key]


def heredoc(path: str, values: dict[str, str], header: str) -> str:
    body = "\n".join(f"{k}={v}" for k, v in values.items())
    # Both directories already exist (the repo is cloned), so this deliberately
    # does not create or re-chmod them — tightening ~/koraa to 700 as a side
    # effect of writing an env file is the kind of change nobody would look for
    # later.
    return (
        f"cat > {path} <<'KORAA_ENV_EOF'\n{header}\n{body}\nKORAA_ENV_EOF\n"
        f"chmod 600 {path}\n"
    )


print("set -euo pipefail")
print(heredoc(
    "$HOME/koraa/.env.prod", compose_env,
    "# Compose-level only: interpolated into DATABASE_URL by\n"
    "# docker-compose.ec2.yml. Generated, do not edit by hand.",
))
print(heredoc(
    "$HOME/koraa/backend/.env.prod", backend_env,
    "# Django production environment. Generated by "
    "infrastructure/aws/gen-prod-env.py.\n"
    "# See backend/.env.prod.example for what each value does.",
))
print('echo "wrote $HOME/koraa/.env.prod and $HOME/koraa/backend/.env.prod"')
print('ls -l "$HOME/koraa/.env.prod" "$HOME/koraa/backend/.env.prod"')

print(f"compose env keys : {', '.join(compose_env)}", file=sys.stderr)
print(f"backend env keys : {', '.join(backend_env)}", file=sys.stderr)
print(f"copied from .env : {len([k for k in COPY_KEYS if local.get(k)])}"
      f"/{len(COPY_KEYS)}", file=sys.stderr)
print("generated fresh  : SECRET_KEY, POSTGRES_PASSWORD", file=sys.stderr)
