# Generated by Django 5.0.6 on 2026-09-02 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_referral_code_referral"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("otp_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Verification OTP",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "phone", "is_used"],
                        name="accounts_ph_user_id_744ca0_idx",
                    )
                ],
            },
        ),
    ]
