# Generated by Django 5.0.6 on 2026-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phone_verification_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="avatar URL"
            ),
        ),
    ]
