# Generated by Django 5.0.6 on 2026-08-11 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_store_domain_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="e.g. bella-fashion.koraa.africa or bellafashion.com",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("subdomain", "Koraa Subdomain"),
                            ("custom_domain", "Custom Domain"),
                        ],
                        default="subdomain",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Verification"),
                            ("failed", "Verification Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "store domain",
                "verbose_name_plural": "store domains",
                "indexes": [
                    models.Index(
                        fields=["domain"], name="domains_sto_domain_1c3568_idx"
                    )
                ],
            },
        ),
    ]
