# Generated by Django 5.0.6 on 2026-09-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """Retargets the example in this field's admin help text at koraa.cm.

    help_text is Django state only — it never reaches the database — so this
    AlterField emits no DDL and takes no lock, whatever the table's size.
    """

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedomain",
            name="domain",
            field=models.CharField(
                help_text="e.g. bella-fashion.koraa.cm or bellafashion.com",
                max_length=255,
                unique=True,
            ),
        ),
    ]
