# Generated by Django 5.0.6 on 2026-08-11 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="business name"),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Store"),
                            ("fashion", "Fashion & Apparel"),
                            ("beauty", "Beauty & Cosmetics"),
                            ("food", "Food & Beverages"),
                            ("electronics", "Electronics"),
                            ("digital", "Digital Products"),
                            ("services", "Services"),
                            ("other", "Other"),
                        ],
                        default="retail",
                        max_length=30,
                        verbose_name="business type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="merchants/logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="merchants/banners/",
                        verbose_name="banner",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="business email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="business phone"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp number"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="CM", max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="subscription tier",
                    ),
                ),
                (
                    "tier_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="tier expires at"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="business verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "merchant",
                "verbose_name_plural": "merchants",
                "ordering": ["-created_at"],
            },
        ),
    ]
