# Generated by Django 5.0.6 on 2026-08-11 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="merchants/identity_docs/"
                    ),
                ),
                ("id_document_verified", models.BooleanField(default=False)),
                (
                    "business_document",
                    models.FileField(
                        blank=True, null=True, upload_to="merchants/business_docs/"
                    ),
                ),
                ("business_document_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity",
                        to="merchants.merchant",
                    ),
                ),
            ],
        ),
    ]
