# Generated by Django 5.0.6 on 2026-08-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_merchant_referral_code_merchant_referred_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstaff",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
