# Generated by Django 5.0.6 on 2026-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_merchantpayoutaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantidentity",
            name="didit_request_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="document_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="verification_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
