# Generated by Django 5.0.6 on 2026-08-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0006_merchantidentity_didit_request_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantidentity",
            name="face_match_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="face_match_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="id_document_back",
            field=models.FileField(
                blank=True, null=True, upload_to="merchants/identity_docs/"
            ),
        ),
        migrations.AddField(
            model_name="merchantidentity",
            name="selfie_with_id",
            field=models.FileField(
                blank=True, null=True, upload_to="merchants/identity_docs/selfies/"
            ),
        ),
    ]
