# Generated by Django 5.0.6 on 2026-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_merchantidentity_face_match_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantidentity",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    (
                        "Refused",
                        "Refused picture wasnt clear and they should upload again",
                    ),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
