# Generated by Django 5.0.6 on 2026-08-22 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0008_alter_merchantidentity_verification_status"),
        ("stores", "0002_store_domain_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="merchantstaff",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="merchantstaff",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Store this member can manage. Empty means the whole account (legacy invites).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_with",
                to="stores.store",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="merchantstaff",
            unique_together={("merchant", "user", "store")},
        ),
    ]
