# Generated by Django 5.0.6 on 2026-09-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0009_alter_merchantstaff_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantidentity",
            name="didit_session_id",
            field=models.UUIDField(
                blank=True, help_text="Didit v3 session UUID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="merchantidentity",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                    ("In Review", "In Review"),
                    ("Abandoned", "Abandoned"),
                    ("Expired", "Expired"),
                    ("Verified", "Verified"),
                    ("Refused", "Refused"),
                ],
                default="Not Started",
                max_length=100,
            ),
        ),
    ]
