# Generated by Django 5.0.6 on 2026-08-11 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="store name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used as subdomain: slug.koraa.africa",
                        max_length=63,
                        unique=True,
                        verbose_name="subdomain slug",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="tagline"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stores/logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stores/favicons/",
                        verbose_name="favicon",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stores/banners/",
                        verbose_name="banner",
                    ),
                ),
                (
                    "theme_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores color overrides, font choices, section ordering, etc.",
                        verbose_name="theme configuration",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Central African CFA Franc (XAF)"),
                            ("NGN", "Nigerian Naira (NGN)"),
                            ("GHS", "Ghanaian Cedi (GHS)"),
                            ("KES", "Kenyan Shilling (KES)"),
                            ("ZAR", "South African Rand (ZAR)"),
                            ("USD", "US Dollar (USD)"),
                            ("EUR", "Euro (EUR)"),
                        ],
                        default="XAF",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="CM", max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="contact phone"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        help_text="e.g. shop.mybrand.com",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="custom domain",
                    ),
                ),
                ("domain_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("preview", "Preview"),
                            ("published", "Published"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="SEO title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="SEO description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "store",
                "verbose_name_plural": "stores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="stores_stor_slug_e2ab60_idx"),
                    models.Index(
                        fields=["merchant", "status"],
                        name="stores_stor_merchan_13c297_idx",
                    ),
                    models.Index(
                        fields=["custom_domain"], name="stores_stor_custom__719a8f_idx"
                    ),
                ],
            },
        ),
    ]
