# Generated by Django 5.0.6 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="domain_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="domain expiration date"
            ),
        ),
    ]
