# Generated by Django 5.0.6 on 2026-09-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """Retargets the example in this field's admin help text at koraa.cm.

    help_text is Django state only — it never reaches the database — so this
    AlterField emits no DDL and takes no lock, whatever the table's size.
    """

    dependencies = [
        ("stores", "0003_store_site_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(
                help_text="Used as subdomain: slug.koraa.cm",
                max_length=63,
                unique=True,
                verbose_name="subdomain slug",
            ),
        ),
    ]
