# Generated by Django 6.0.4 on 2026-09-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_alter_store_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_showcased",
            field=models.BooleanField(
                default=False,
                help_text="Display this store on the public Koraa showcase page",
            ),
        ),
    ]
